

services:
  cykormongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cykorroot
      - MONGO_INITDB_ROOT_PASSWORD=cykorpass

  cykorbackend:
    build: ./cykorbackend
    ports:
      - "5000:5000"
    depends_on:
      - cykormongo
    environment:
      - MONGO_URI=mongodb://cykorroot:cykorpass@cykormongo:27017/cykordb?authSource=admin

  cykorfrontend:
    build: ./cykorfrontend
    ports:
      - "3000:80"
    depends_on:
      - cykorbackend

volumes:
  mongo-data:
